import type { Metadata } from "next";
import { Roboto, Roboto_Serif, Roboto_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { Container } from "@c/container";
import { Button } from "@c/ui/button";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoSerif.variable} ${robotoMono.variable} antialiased`}
      >
        <header className="sticky top-0 flex items-center h-16 bg-background shadow">
          <Container className="grid grid-cols-3 items-center">
            <span className="font-semibold text-2xl">Logo</span>
            <nav className="flex items-center gap-4 mx-auto">
              <Link href="/">Home</Link>
              <Link href="/typography">Typography</Link>
            </nav>
            <Button className="ml-auto">Secondary</Button>
          </Container>
        </header>{" "}
        {children}
      </body>
    </html>
  );
}
